### ISSUE TITLE
Feature - Recurring Run model deployment

### ISSUE THREAD

**Issue by johnhoman** [johnhoman/kfp-releaser#4]
Ideally, it would be possible to create a model from a run artifact (Model)

Updated models should replace existing model deployments (from the same recurring run) or at least specify a traffic splitting policy.

```yaml
kind: RecurringRun
spec:
  produces:
  - model:
      template:
        metadata:
          name: model
        spec:
          predictor:
            sklearn:
              storageUri: minio://...
```
